#pragma once

typedef struct _S_PT_CHANNEL_NICKNAME
{
	WCHAR USER_ID[32];
	WCHAR NICK_NAME[32];
} S_PT_CHANNEL_NICKNAME;

typedef struct _S_PT_CHANNEL_NICKNAME_SUCC_U
{
	WCHAR USER_ID[32];
	WCHAR NICK_NAME[32];
} S_PT_CHANNEL_NICKNAME_SUCC_U;

typedef struct _S_PT_CHANNEL_NICKNAME_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_CHANNEL_NICKNAME_FAIL_U;

